### PR TITLE
Generate IDC box headers

### PR DESCRIPTION
**Pull request by dbrgn**
Part numbers:

- CNCTECH_3020-xx-0300-XX: http://cnctech.us/pdfs/3020-XX-0300-00.pdf
- CNCTECH_3120-xx-0300-XX: http://cnctech.us/pdfs/3120-XX-0300-00.pdf
- CNCTECH_3220-xx-0300-XX: http://cnctech.us/pdfs/3220-XX-0300-00.pdf

Generator script: https://github.com/LibrePCB/librepcb-parts-generator/pull/47

screenshot

### CODE REVIEW

**Comment by dbrgn** [comment]
Updated with leads on documentation layer.

**Comment by ubruhin** [comment]
- The packages could be added to the "Pin Header" category too.
- The hidden grab area overlaps with pads and thus could be very annoying when connecting traces to the pads. I would completely remove the grab area because currently the board editor works very bad with too much grab areas.
- The pin-1 marking is nice, but somehow I miss the triangle which is also on the package body. Maybe add the triangle to the documentation layer?
- On the documentation layer, it would be nice to see the actual pin headers (top view, small squares).
- The trailing "-XX" in their names seems to be a placeholder for the contact plating. But I wonder if it would be better to create separate packages for the different platings (in https://github.com/LibrePCB-Libraries/Cinch_Connectivity_Solutions.lplib/pull/1 you didn't use a placeholder)...

**Comment by dbrgn** [comment]
> The packages could be added to the "Pin Header" category too.

Done

> The hidden grab area overlaps with pads and thus could be very annoying when connecting traces to the pads. I would completely remove the grab area because currently the board editor works very bad with too much grab areas.

Hidden grab areas don't seem to work in the board editor at all right now :slightly_smiling_face: 

> The pin-1 marking is nice, but somehow I miss the triangle which is also on the package body. Maybe add the triangle to the documentation layer?

Will do!

> On the documentation layer, it would be nice to see the actual pin headers (top view, small squares).

They would overlap with the SMD pads on the doc layer.

> The trailing "-XX" in their names seems to be a placeholder for the contact plating. But I wonder if it would be better to create separate packages for the different platings (in LibrePCB-Libraries/Cinch_Connectivity_Solutions.lplib#1 you didn't use a placeholder)...

I'd ignore them for now. I'll add the X placeholder for the SMA connector too.

**Comment by dbrgn** [comment]
@ubruhin pin1 markings are now added. Good to merge?

**Review by ubruhin — APPROVED** [review]
Perfect, thanks! :+1:

**Pull request merged**
